//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCL.GTAIV.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCL.GTAIV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carsteal
        ///coop_bombdbase
        ///coop_drugfac
        ///coop_swatasslt
        ///deathmatch_cr
        ///freemode_cr
        ///initialnet
        ///mpcellphone
        ///mpcellphonecalling
        ///mpcellphonemain
        ///mpcellphonenetwork
        ///mpcellphoneparty
        ///network_main
        ///network_startup
        ///party_mode
        ///races_cr
        ///roving_cr
        ///speechcontrol_net
        ///tm_base
        ///tm_vip
        ///txtlnkmiss_net
        ///.
        /// </summary>
        internal static string IV_MP_Scripts {
            get {
                return ResourceManager.GetString("IV_MP_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to advanced_car_actions
        ///ambairpotarea
        ///ambatmq
        ///ambbar
        ///ambbarrier
        ///ambbeggar
        ///ambblkhawk
        ///ambbouncer
        ///ambbridgepatrol
        ///ambbusker
        ///ambcabaret
        ///ambcargoholddoors
        ///ambchurchdoors
        ///ambclublights
        ///ambcomedyclub
        ///ambcontrolloader
        ///ambcontrolmain
        ///ambdealer
        ///ambdebug
        ///ambfloater
        ///ambgerry3doorlock
        ///ambhelicopter
        ///ambhomelandcordon
        ///ambhomelandfed
        ///ambhomelandsirens
        ///ambhotel
        ///ambinternetcafe
        ///ambjerseydocksgates
        ///ambjimslocks
        ///ambliftdoors
        ///ambnightclubext
        ///ambpimpnpros
        ///ambpoledancer
        ///ambpolrdblk
        ///ambpreacher
        ///amb [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IV_Scripts {
            get {
                return ResourceManager.GetString("IV_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basejumplauncher_mp
        ///debug_net
        ///e2_deathmatch
        ///e2_freemode
        ///e2_party_mode
        ///e2_quickdm
        ///e2_races
        ///initialnet
        ///mpcellphone
        ///mpcellphonecalling
        ///mpcellphonemain
        ///mpcellphonenetwork
        ///mpcellphoneparty
        ///network_main
        ///network_session_net
        ///network_startup
        ///parachutelauncher_mp
        ///parachute_player_mp
        ///speechcontrol_net
        ///.
        /// </summary>
        internal static string TBOGT_MP_Scripts {
            get {
                return ResourceManager.GetString("TBOGT_MP_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ability_backup
        ///ability_bomb
        ///ability_gun_car
        ///ability_vehicle
        ///advanced_car_actions
        ///air_hockey
        ///air_hockey_trigger
        ///ambairpotarea
        ///ambatmq
        ///ambbar
        ///ambbarrier
        ///ambbeggar
        ///ambblkhawk
        ///ambbouncer
        ///ambbridgepatrol
        ///ambbusker
        ///ambcabaret
        ///ambcargoholddoors
        ///ambchurchdoors
        ///ambclublights
        ///ambcomedyclub
        ///ambcontrolloader
        ///ambcontrolmain
        ///ambdealer
        ///ambdebug
        ///ambdrinking
        ///ambfloater
        ///ambfoodeating
        ///ambfunfair
        ///ambgerry3doorlock
        ///ambhelicopter
        ///ambhomelandcordon
        ///ambhotel
        ///ambinternetcafe
        ///ambjerseydocksgates
        ///am [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TBOGT_Scripts {
            get {
                return ResourceManager.GetString("TBOGT_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to car_dmge_wdgt_net
        ///car_rec_wdgt_net
        ///creator_debug_net
        ///debug_net
        ///drawrect_debug_net
        ///drawsprit_debug_net
        ///drawtext_debug_net
        ///e1_chapter
        ///e1_chopper
        ///e1_deathmatch
        ///e1_destroyvan
        ///e1_freemode
        ///e1_mostwanted
        ///e1_party_mode
        ///e1_quickdm
        ///e1_races
        ///e1_turfwar
        ///initialnet
        ///locates_debug_net
        ///locates_widget_net
        ///mpcellphone
        ///mpcellphonecalling
        ///mpcellphonemain
        ///mpcellphonenetwork
        ///mpcellphoneparty
        ///network_main
        ///network_session_net
        ///network_startup
        ///offset_widget_net
        ///places_debug_net
        ///races_debug_net
        ///scrguide [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TLAD_MP_Scripts {
            get {
                return ResourceManager.GetString("TLAD_MP_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ability_backup
        ///ability_bomb
        ///ability_gun_car
        ///ability_stats
        ///ability_vehicle
        ///abil_weap_pickup
        ///advanced_car_actions
        ///air_hockey
        ///air_hockey_trigger
        ///ambairpotarea
        ///ambatmq
        ///ambbar
        ///ambbarrier
        ///ambbeggar
        ///ambblkhawk
        ///ambbouncer
        ///ambbridgepatrol
        ///ambbusker
        ///ambcabaret
        ///ambcargoholddoors
        ///ambchurchdoors
        ///ambclubhouse
        ///ambclublights
        ///ambcomedyclub
        ///ambcontrolloader
        ///ambcontrolmain
        ///ambdealer
        ///ambfloater
        ///ambgentlemansclub
        ///ambgerry3doorlock
        ///ambhelicopter
        ///ambhomelandcordon
        ///ambhomelandfed
        ///ambhomelandsirens        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TLAD_Scripts {
            get {
                return ResourceManager.GetString("TLAD_Scripts", resourceCulture);
            }
        }
    }
}
